### ISSUE TITLE
Update Commented Code from Lesson

### ISSUE THREAD

**Issue by DanielleQuinn** [DanielleQuinn/next-steps-in-r#4]
Hi @fmichonneau I've added commented code from the first half of the lesson; when you have a chance could you add your notes and then I'll let the attendees know that it has been posted? Thanks!
DQ

**Comment by fmichonneau** [comment]
Do you still have the copy of the code I typed on your laptop during the workshop? Because I improvised a little and deviated from what I had planned... If you do, could you please add it below yours, and I'll add comments. Thanks!
